### ISSUE TITLE
Parse exception on providing a List type as value to `not` with `"in"` operator

### ISSUE THREAD

**Issue by carlomigueldy** [supabase/postgrest-dart#36]
# Bug report

## Describe the bug

The `.not` method does not work as expected. And receiving a parse exception instead.

```
 "failed to parse filter (not.in.[])" (line 1, column 8)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Make a query with the `not` query builder method and use 'in' as the operator, and provide an array value.

## Expected behavior

It should query WHERE NOT IN

## Screenshots

![image](https://user-images.githubusercontent.com/45052332/127978666-cd8e9a2f-a75e-4ceb-9752-8a21f83d6cf0.png)

## System information

- OS: Windows
- Version of supabase dart: ^0.0.7=

**Comment by dshukertjr** [comment]
Hey @carlomigueldy!

Thank you so much for reporting this! This issue should be now fixed with the latest version of `postgrest`, `supabase_dart`, and `supabase_flutter` package!

**Comment by bdlukaa** [comment]
@dshukertjr this issue still happens if the list is a list of strings

**Comment by dshukertjr** [comment]
@bdlukaa Like this? https://github.com/supabase/postgrest-dart/blob/master/test/filter_test.dart#L23
Do you have a specific code that throws an error?

**Comment by bdlukaa** [comment]
@dshukertjr I got it working using:

```dart
.not('id', 'in', '(${exceptFor.map((s) => '"$s"').join(',')})')
```

because my strings needed the "" to work, without them it just doesnt work.
